apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
    -  name: ubuntu
       image: ubuntu
       command: ["sleep", "3600"]
       securityContext:
         runAsUser: 10000
         capabilities:
           add: ["MAC_ADMIN"] ## Capabilities are suported only at container level
